trainer:
  max_epochs: 300
  log_every_n_steps: 10
  accelerator: gpu
  gradient_clip_val: 0.5
  default_root_dir: logs/FTW-25-Experiments-2-2/experiment-2-2.1-finetuning
  devices:
    - 0
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        mode: min
        save_top_k: 0
        save_last: true
        filename: "{epoch}-{val_loss:.2f}"
model:
  class_path: src.trainers.CustomSemanticSegmentationTask
  init_args:
    class_weights: [0.33,0.34,0.33]
    loss: "ce"
    model: "unet"
    backbone: "efficientnet-b3"
    weights: true
    patch_weights: false
    in_channels: 8
    num_classes: 3
    num_filters: 64
    ignore_index: 3
    lr: 1e-3
    patience: 100
data:
  class_path: src.datamodules.FTWDataModule
  init_args:
    batch_size: 32
    num_workers: 12
    train_countries:
      - cambodia
      - vietnam
    val_countries:
      - cambodia
      - vietnam
    test_countries:
      - cambodia
      - vietnam
  dict_kwargs:
    root: data/ftw
    load_boundaries: True
seed_everything: 7