trainer:
  max_epochs: 100
  log_every_n_steps: 100
  accelerator: gpu
  default_root_dir: logs/FTW-Release-Full-3-class
  devices:
    - 0
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: ftw-baselines
      name: ftw-pure-0418
      log_model: false
      tags:
        - 3class
        - austria
        - pure-efnet7
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val/iou_macro
        mode: max
        save_top_k: 1
        save_last: true
        filename: "{epoch}-{val//iou:.3f}"
model:
  class_path: ftw_tools.training.trainers.CustomSemanticSegmentationTask
  init_args:
    class_weights: [0.05, 0.2, 0.75]
    loss: "logcoshdice"
    model: "unet"
    backbone: "efficientnet-b7"
    weights: true
    patch_weights: false
    in_channels: 8
    num_classes: 3
    num_filters: 64
    ignore_index: 3
    lr: 2e-4
    patience: 100
data:
  class_path: ftw_tools.training.datamodules.FTWDataModule
  init_args:
    batch_size: 4
    num_workers: 4
    random_shuffle: true
    train_countries:
      - austria
    val_countries:
      - austria
    test_countries:
      - austria
  dict_kwargs:
    root: data/ftw
    load_boundaries: true
    brightness_aug: true
    resize_aug: true
seed_everything: 7
