# lightning.pytorch==2.5.4
seed_everything: 7
trainer:
  accelerator: gpu
  strategy: auto
  devices:
  - 0
  num_nodes: 1
  precision: null
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      name: dev-run
      save_dir: .
      version: null
      offline: false
      dir: null
      id: null
      anonymous: null
      project: ftw-baselines
      log_model: false
      experiment: null
      prefix: ''
      checkpoint_name: null
      entity: null
      notes: null
      tags:
      - dev
      config: null
      config_exclude_keys: null
      config_include_keys: null
      allow_val_change: null
      group: null
      job_type: null
      mode: null
      force: null
      reinit: null
      resume: null
      resume_from: null
      fork_from: null
      save_code: null
      tensorboard: null
      sync_tensorboard: null
      monitor_gym: null
      settings: null
  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      dirpath: null
      filename: '{epoch}-{val_loss:.2f}'
      monitor: val_loss
      verbose: false
      save_last: true
      save_top_k: 0
      save_on_exception: false
      save_weights_only: false
      mode: min
      auto_insert_metric_name: true
      every_n_train_steps: null
      train_time_interval: null
      every_n_epochs: null
      save_on_train_epoch_end: null
      enable_version_counter: true
  fast_dev_run: false
  max_epochs: 2
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 16
  limit_val_batches: 8
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: 1
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: logs/FTW-Dev
  model_registry: null
model:
  class_path: ftw_tools.training.trainers.CustomSemanticSegmentationTask
  init_args:
    model: unet
    backbone: efficientnet-b3
    weights: true
    in_channels: 8
    num_classes: 3
    num_filters: 64
    loss: ce
    class_weights:
    - 0.05
    - 0.2
    - 0.75
    ignore_index: 3
    pixel_weight_scale: null
    lr: 0.001
    patience: 100
    patch_weights: false
    freeze_backbone: false
    freeze_decoder: false
    edge_agreement_loss: false
    model_kwargs: {}
data:
  class_path: ftw_tools.training.datamodules.FTWDataModule
  init_args:
    root: data/ftw
    batch_size: 4
    num_workers: 2
    train_countries:
    - austria
    val_countries:
    - austria
    test_countries:
    - austria
    temporal_options: stacked
    num_samples: 128
    percent_samples: -1.0
    seed: 42
    random_shuffle: true
    resize_factor: null
    brightness_aug: false
    preprocess_aug: true
    resize_aug: true
    load_boundaries: true
    transforms: null
    checksum: false
    load_edges: false
    swap_order: false
    verbose: true
optimizer: null
lr_scheduler: null
ckpt_path: null
