trainer:
  max_epochs: 200 # TODO: change me
  log_every_n_steps: 10
  accelerator: gpu
  default_root_dir: logs/FTW-25-Experiments-3/experiment-3.1-finetuning
  devices:
    - 0
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: val_loss
        mode: min
        save_top_k: 1
        save_last: true
        filename: "{epoch}-{val_loss:.2f}"
model:
  class_path: ftw.trainers.CustomSemanticSegmentationTask
  init_args:
    class_weights: [0.04,0.08,0.88] #TODO: change me
    loss: "ce"
    model: "unet"
    backbone: "efficientnet-b3"
    weights: true
    patch_weights : false
    in_channels: 8
    num_classes: 3
    num_filters: 64
    ignore_index: 3
    lr: 1e-3
    patience: 100
data:
  class_path: ftw.datamodules.FTWDataModule
  init_args:
    batch_size: 32
    num_workers: 12 
    num_samples: -1
    train_countries:
      - india
    val_countries:
      - india
    test_countries:
      - india
  dict_kwargs:
    root: data/ftw
    load_boundaries: True
seed_everything: 7