name: pytest

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  tests:
    # See https://stackoverflow.com/questions/72703363/how-to-activate-conda-environment-in-github-actions
    defaults:
      run:
        shell: bash -l {0}
    name: python-matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ftw
          environment-file: env.yml
          auto-activate-base: false
      - name: Install Python dependencies
        run: pip install -e .[dev]
      - name: Execute test suites
        run: pytest src/tests
