name: pytest

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[all]'
      - name: Run pre-commit
        run: pre-commit run --all-files

  tests:
    name: Run tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-13
          - macos-latest
        python-version:
          - "3.11"
          - "3.12"
      fail-fast: true
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[all]'
      - name: install opencv headless for ubuntu only
        if: runner.os == 'Linux'
        run: |
          pip uninstall -y opencv-python || true
          pip install opencv-python-headless
      - name: install numpy <2 for macos-13 only
        if: matrix.os == 'macos-13'
        run: |
          pip install numpy<2
      - name: Execute tests
        run: pytest