name: pytest

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
      - uses: actions/checkout@v4
      - uses: pre-commit/action@v3.0.0

  tests:
    # See https://stackoverflow.com/questions/72703363/how-to-activate-conda-environment-in-github-actions
    defaults:
      run:
        shell: bash -l {0}
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.11"
          - "3.12"
#         - "3.13"
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: ftw
          environment-file: env.yml
          auto-activate-base: false
      - name: Install Python version ${{ matrix.python-version }}
        run: conda install python=${{ matrix.python-version }}
      - name: Install Python dependencies
        run: pip install -e .[dev]
      - name: Download model
        run: wget https://github.com/fieldsoftheworld/ftw-baselines/releases/download/v1/3_Class_FULL_FTW_Pretrained.ckpt
      - name: Execute help tests
        run: pytest src/tests/test_help.py
      - name: Execute data tests
        run: pytest src/tests/test_data.py
      - name: Execute model tests
        run: pytest src/tests/test_model.py
      - name: Execute inference tests
        run: pytest src/tests/test_inference.py
      
